apiVersion: apps/v1
kind: Deployment
metadata:
  name: pradysagican-api
  labels:
    app: pradysagican-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pradysagican-api
  template:
    metadata:
      labels:
        app: pradysagican-api
    spec:
      containers:
        - name: api
          image: pradysagican:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: PRADY_ENV
              value: production
            - name: PRADY_PORT
              value: "8000"
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 20
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"

