"""Upgrade feature catalog aligned to the unified feature tracker (F01-F51)."""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class UpgradeFeature:
    feature_id: str
    name: str
    workstream: str
    benchmark_link: str


FEATURES_51: list[UpgradeFeature] = [
    UpgradeFeature("F01", "MCP client integration", "A", "TauBench/OSWorld"),
    UpgradeFeature("F02", "MCP server discovery/registry bridge", "A", "TauBench"),
    UpgradeFeature("F03", "Crawl4AI URL markdown extraction", "A", "HLE"),
    UpgradeFeature("F04", "Crawl4AI parallel crawl mode", "A", "HLE/GAIA"),
    UpgradeFeature("F05", "Crawl session persistence", "A", "HLE/WebArena"),
    UpgradeFeature("F06", "Scrapling adaptive DOM extractor", "A", "WebArena"),
    UpgradeFeature("F07", "E2B sandbox Python executor", "A", "SWE/Terminal"),
    UpgradeFeature("F08", "E2B sandbox shell executor", "A", "Terminal"),
    UpgradeFeature("F09", "SSH execution backend", "A", "Terminal"),
    UpgradeFeature("F10", "Shell history manager", "A", "Terminal"),
    UpgradeFeature("F11", "Repo context builder", "H", "SWE"),
    UpgradeFeature("F12", "Test-repair loop engine", "H", "SWE"),
    UpgradeFeature("F13", "Semantic code search integration", "H", "SWE"),
    UpgradeFeature("F14", "Mem0 auto-extraction middleware", "B", "TauBench"),
    UpgradeFeature("F15", "Mem0 contradiction resolution bridge", "B", "GPQA/HLE"),
    UpgradeFeature("F16", "Mem0 retrieval injection layer", "B", "HLE"),
    UpgradeFeature("F17", "Session log store (SQLite)", "B", "TauBench"),
    UpgradeFeature("F18", "FTS5 index and recall API", "B", "TauBench"),
    UpgradeFeature("F19", "Skills persistence format + loader", "B", "SWE/TauBench"),
    UpgradeFeature("F20", "Skill auto-generation from trajectories", "B", "SWE"),
    UpgradeFeature("F21", "LiteLLM provider router", "E", "GPQA/HLE"),
    UpgradeFeature("F22", "Provider fallback and failover policies", "E", "Reliability"),
    UpgradeFeature("F23", "Spend guardrails and budget routing", "E", "Prod"),
    UpgradeFeature("F24", "Runtime selector (vLLM/MLX/Ollama)", "E", "Throughput"),
    UpgradeFeature("F25", "vLLM backend adapter", "E", "Coding/Agent"),
    UpgradeFeature("F26", "MLX backend adapter", "E", "Local adoption"),
    UpgradeFeature("F27", "CodeAgent core", "C", "SWE/Terminal"),
    UpgradeFeature("F28", "CodeAgent-to-tool API bridge", "C", "SWE"),
    UpgradeFeature("F29", "Typed agent contracts (Pydantic)", "C", "TauBench"),
    UpgradeFeature("F30", "Contract validation middleware", "C", "Reliability"),
    UpgradeFeature("F31", "Prompt registry with ell", "D", "GPQA/HLE"),
    UpgradeFeature("F32", "Prompt A/B experiment harness", "D", "GPQA"),
    UpgradeFeature("F33", "Domain CoT templates (STEM)", "D", "GPQA"),
    UpgradeFeature("F34", "Self-consistency sampling engine", "D", "GPQA"),
    UpgradeFeature("F35", "Multi-model voting/aggregation", "D", "GPQA/HLE"),
    UpgradeFeature("F36", "Uncertainty calibration routing", "D", "HLE/Safety"),
    UpgradeFeature("F37", "Telemetry latency tracking", "F", "All"),
    UpgradeFeature("F38", "Cost estimation tracking", "F", "Prod"),
    UpgradeFeature("F39", "Token throughput tracking", "F", "All"),
    UpgradeFeature("F40", "VRAM/runtime memory tracking", "F", "All"),
    UpgradeFeature("F41", "Benchmark evidence logger", "H", "All"),
    UpgradeFeature("F42", "ARC test-time adaptation scaffold", "H", "ARC"),
    UpgradeFeature("F43", "ARC symbolic grid utilities", "H", "ARC"),
    UpgradeFeature("F44", "ARC MCTS program candidate search", "H", "ARC"),
    UpgradeFeature("F45", "HLE retrieval pre-seeding pipeline", "H", "HLE"),
    UpgradeFeature("F46", "Telegram gateway", "G", "TauBench"),
    UpgradeFeature("F47", "Channel routing into orchestrator", "G", "Agent"),
    UpgradeFeature("F48", "APScheduler cron module", "G", "Agent automation"),
    UpgradeFeature("F49", "Scheduled task persistence + retries", "G", "Agent automation"),
    UpgradeFeature("F50", "CLI/API controls for new capabilities", "G", "Usability"),
    UpgradeFeature("F51", "Full root wiring in PradysagicanGod", "All", "All"),
]


OMEGA_PART2_FEATURES: list[UpgradeFeature] = [
    UpgradeFeature("O01", "OmegaConsciousnessStack scaffold", "Omega-I", "Reasoning/HLE"),
    UpgradeFeature("O02", "StrangeLoopDetector scaffold", "Omega-I", "Reasoning"),
    UpgradeFeature("O03", "ConsciousnessMetric scaffold", "Omega-I", "Reasoning"),
    UpgradeFeature("O04", "CScoreMaximizer scaffold", "Omega-I", "Reasoning"),
    UpgradeFeature("O05", "ElevationTrigger scaffold", "Omega-I", "Stability"),
    UpgradeFeature("O06", "OMEGA consciousness API wiring", "Omega-Integration", "API"),
    UpgradeFeature("O07", "FactorGraphMemory scaffold", "Omega-I", "Memory"),
    UpgradeFeature("O08", "POMDP decision scaffold", "Omega-I", "Planning"),
    UpgradeFeature("O09", "TheoryOfMindSigma scaffold", "Omega-I", "Multi-agent"),
    UpgradeFeature("O10", "MentalImagery scaffold", "Omega-I", "Planning"),
    UpgradeFeature("O11", "Impasse reflection scaffold", "Omega-I", "Reliability"),
    UpgradeFeature("O12", "UnifiedLearning scaffold", "Omega-I", "Learning"),
    UpgradeFeature("O13", "CognitiveCycleTimer scaffold", "Omega-I", "Realtime"),
    UpgradeFeature("O14", "ECANAttention scaffold", "Omega-I", "Reasoning"),
    UpgradeFeature("O15", "ConceptFormation scaffold", "Omega-I", "Learning"),
    UpgradeFeature("O16", "CreativeHypothesisGen scaffold", "Omega-I", "Research"),
    UpgradeFeature("O17", "GoalHierarchy scaffold", "Omega-I", "Planning"),
    UpgradeFeature("O18", "AttentionBudget scaffold", "Omega-I", "Efficiency"),
    UpgradeFeature("O19", "PsychoHistoryModel scaffold", "Omega-I", "Behavior"),
    UpgradeFeature("O20", "SVD task adapter scaffold", "Omega-I", "Inference"),
    UpgradeFeature("O21", "Inference-time weight switch scaffold", "Omega-I", "Inference"),
    UpgradeFeature("O22", "Task embedder scaffold", "Omega-I", "Inference"),
    UpgradeFeature("O23", "SVD component library scaffold", "Omega-I", "Inference"),
    UpgradeFeature("O24", "ConstitutionEngine scaffold", "Omega-Safety", "Safety"),
    UpgradeFeature("O25", "SelfCritiqueReviser scaffold", "Omega-Safety", "Safety"),
    UpgradeFeature("O26", "RecursiveRewardModel scaffold", "Omega-Safety", "Alignment"),
    UpgradeFeature("O27", "AmplificationLoop scaffold", "Omega-Safety", "Alignment"),
    UpgradeFeature("O28", "DebateOverseer scaffold", "Omega-Safety", "Alignment"),
    UpgradeFeature("O29", "ActivationSAE scaffold", "Omega-Interpretability", "Safety"),
    UpgradeFeature("O30", "FeatureSteeringVectors scaffold", "Omega-Interpretability", "Safety"),
    UpgradeFeature("O31", "SteeringController scaffold", "Omega-Interpretability", "Safety"),
    UpgradeFeature("O32", "CircuitTracer scaffold", "Omega-Interpretability", "Safety"),
    UpgradeFeature("O33", "FeatureAttribution scaffold", "Omega-Interpretability", "Safety"),
    UpgradeFeature("O34", "HallucinationCircuit scaffold", "Omega-Interpretability", "Safety"),
    UpgradeFeature("O35", "SelfOperatingComputer scaffold", "Omega-ComputerUse", "OSWorld"),
    UpgradeFeature("O36", "MultimodalScreenReader scaffold", "Omega-ComputerUse", "OSWorld"),
    UpgradeFeature("O37", "AccessibilityTreeParser scaffold", "Omega-ComputerUse", "OSWorld"),
    UpgradeFeature("O38", "ActionGrounder scaffold", "Omega-ComputerUse", "OSWorld"),
    UpgradeFeature("O39", "BrowserController scaffold", "Omega-ComputerUse", "GAIA/OSWorld"),
    UpgradeFeature("O40", "DesktopController scaffold", "Omega-ComputerUse", "OSWorld"),
    UpgradeFeature("O41", "ErrorRecoveryFlow scaffold", "Omega-ComputerUse", "OSWorld"),
    UpgradeFeature("O42", "MemoryCitadelAPI 12-tier scaffold", "Omega-Memory", "Long-context"),
    UpgradeFeature("O43", "TierRouter policy scaffold", "Omega-Memory", "Long-context"),
    UpgradeFeature("O44", "Episodic-to-semantic consolidation scaffold", "Omega-Memory", "Long-context"),
    UpgradeFeature("O45", "Cross-tier memory garbage collector", "Omega-Memory", "Long-context"),
    UpgradeFeature("O46", "Cross-tier memory synchronizer", "Omega-Memory", "Long-context"),
    UpgradeFeature("O47", "Cross-tier memory compressor", "Omega-Memory", "Long-context"),
    UpgradeFeature("O48", "Replay rehearsal buffer", "Omega-Memory", "Long-context"),
    UpgradeFeature("O49", "AutoBenchmarker scaffold", "Omega-Bench", "All"),
    UpgradeFeature("O50", "WeaknessFinder scaffold", "Omega-Bench", "All"),
    UpgradeFeature("O51", "BenchmarkOracle scaffold", "Omega-Bench", "All"),
    UpgradeFeature("O52", "HumanEvalQueue scaffold", "Omega-Bench", "All"),
    UpgradeFeature("O53", "RegressionGuard scaffold", "Omega-Bench", "All"),
    UpgradeFeature("O54", "PerformanceLeaderboard scaffold", "Omega-Bench", "All"),
    UpgradeFeature("O55", "GoalPreservationLock scaffold", "Omega-Safety", "Safety"),
    UpgradeFeature("O56", "CapabilityOntology scaffold", "Omega-Safety", "Safety"),
    UpgradeFeature("O57", "ImpactMinimizer scaffold", "Omega-Safety", "Safety"),
    UpgradeFeature("O58", "TriplockApproval scaffold", "Omega-Safety", "Safety"),
    UpgradeFeature("O59", "SafeRSICage scaffold", "Omega-Safety", "Safety"),
    UpgradeFeature("O60", "CorrigibilityModule scaffold", "Omega-Safety", "Safety"),
    UpgradeFeature("O61", "Decentralized identity + ASI token stubs", "Omega-Decentralized", "Ecosystem"),
    UpgradeFeature("O62", "Marketplace/data/fetch agent stubs", "Omega-Decentralized", "Ecosystem"),
    UpgradeFeature("O63", "MeTTa runtime scaffold", "Omega-NeuroSymbolic", "Reasoning"),
    UpgradeFeature("O64", "HardwareAutoSelect scaffold", "Omega-Infrastructure", "Efficiency"),
    UpgradeFeature("O65", "EnergyAwareScheduler scaffold", "Omega-Infrastructure", "Efficiency"),
    UpgradeFeature("O66", "Modal/Daytona infra stubs", "Omega-Infrastructure", "Deployment"),
    UpgradeFeature("O67", "HermesSSH + Kubernetes stubs", "Omega-Infrastructure", "Terminal/Agent"),
    UpgradeFeature("O68", "P2P mesh + federated learning stubs", "Omega-Infrastructure", "Scalability"),
    UpgradeFeature("O69", "OMEGA feature flags in config", "Omega-Integration", "Safe rollout"),
    UpgradeFeature("O70", "OMEGA CLI command + chat shortcut", "Omega-Integration", "Usability"),
    UpgradeFeature("O71", "OMEGA API status/update endpoints", "Omega-Integration", "Usability"),
    UpgradeFeature("O72", "OMEGA subsystem loading in God core", "Omega-Integration", "Stability"),
    UpgradeFeature("O73", "OMEGA optional dependency bundle", "Omega-Integration", "Packaging"),
    UpgradeFeature("O74", "Upgrade tracker OMEGA sync section", "Omega-Integration", "Program management"),
    UpgradeFeature("O75", "Release-readiness OMEGA section", "Omega-Integration", "Program management"),
    UpgradeFeature("O76", "big-AGI style persona/beam UX layer", "Omega-Backlog", "UX"),
    UpgradeFeature("O77", "Voice + PDF UX pipeline", "Omega-Backlog", "UX"),
    UpgradeFeature("O78", "E2B persistent/snapshot orchestration", "Omega-Backlog", "SWE/Terminal"),
    UpgradeFeature("O79", "Langfuse benchmark correlator production export", "Omega-Backlog", "All"),
    UpgradeFeature("O80", "50-benchmark daily scheduler wiring", "Omega-Backlog", "All"),
    UpgradeFeature("O81", "Triplock formal proof adapter", "Omega-Backlog", "Safety"),
    UpgradeFeature("O82", "Live ASI wallet + settlement integration", "Omega-Backlog", "Ecosystem"),
    UpgradeFeature("O83", "Neuromorphic backend adapter", "Omega-Backlog", "Efficiency"),
    UpgradeFeature("O84", "Real P2P mesh transport integration", "Omega-Backlog", "Scalability"),
    UpgradeFeature("O85", "OMEGA phased roadmap executor automation", "Omega-Backlog", "Program management"),
]
